"""QuantumTouch declarative specs."""

from glove80.base import LayerRef

COMMON_FIELDS = {
    "keyboard": "glove80",
    "firmware_api_version": "1",
    "locale": "en-US",
    "unlisted": False,
    "creator": "basnijholt",
    "custom_defined_behaviors": '// "Meh" key to define custom commands in e.g., VSCode\n'
    "// NOTE: Using right-side keys because of Keyd remaps in Linux\n"
    "#define MEH_KEY RA(RC(RIGHT_SHIFT))\n"
    "\n"
    "behaviors {\n"
    "    // Shift + Backspace for Delete\n"
    "    bspc_del: backspace_delete {\n"
    '        compatible = "zmk,behavior-mod-morph";\n'
    "        #binding-cells = <0>;\n"
    "        bindings = <&kp BACKSPACE>, <&kp DELETE>;\n"
    "        mods = <(MOD_LSFT|MOD_RSFT)>;\n"
    "        keep-mods = <0>;\n"
    "    };\n"
    "\n"
    "    // Double tap to toggle caps word\n"
    "    td_caps_lshift: tap_dance_caps_lshift {\n"
    '        compatible = "zmk,behavior-tap-dance";\n'
    "        #binding-cells = <0>;\n"
    "        tapping-term-ms = <200>;\n"
    "        bindings = <&kp LSHIFT>, <&caps_word>;\n"
    "    };\n"
    "    td_caps_rshift: tap_dance_caps_rshift {\n"
    '        compatible = "zmk,behavior-tap-dance";\n'
    "        #binding-cells = <0>;\n"
    "        tapping-term-ms = <200>;\n"
    "        bindings = <&kp RSHIFT>, <&caps_word>;\n"
    "    };\n"
    "    // (Sticky) Double tap to toggle caps word\n"
    "    td_caps_lshift_sk: tap_dance_caps_lshift_sk {\n"
    '        compatible = "zmk,behavior-tap-dance";\n'
    "        #binding-cells = <0>;\n"
    "        tapping-term-ms = <200>;\n"
    "        bindings = <&sk LSHIFT>, <&caps_word>;\n"
    "    };\n"
    "    td_caps_rshift_sk: tap_dance_caps_rshift_sk {\n"
    '        compatible = "zmk,behavior-tap-dance";\n'
    "        #binding-cells = <0>;\n"
    "        tapping-term-ms = <200>;\n"
    "        bindings = <&sk RSHIFT>, <&caps_word>;\n"
    "    };\n"
    "\n"
    "    // Double tap Command for Enter\n"
    "    td_lgui_enter: td_lgui_enter {\n"
    '        compatible = "zmk,behavior-tap-dance";\n'
    "        #binding-cells = <0>;\n"
    "        tapping-term-ms = <200>;\n"
    "        bindings = <&kp LGUI>, <&kp ENTER>;\n"
    "    };\n"
    "    // (Sticky) Double tap Command for Enter\n"
    "    td_lgui_enter_sk: td_lgui_enter_sk {\n"
    '        compatible = "zmk,behavior-tap-dance";\n'
    "        #binding-cells = <0>;\n"
    "        tapping-term-ms = <200>;\n"
    "        bindings = <&sk LGUI>, <&kp ENTER>;\n"
    "    };\n"
    "\n"
    "    behavior_caps_word {\n"
    "        continue-list = <\n"
    "            UNDERSCORE\n"
    "            BACKSPACE DELETE\n"
    "            N1 N2 N3 N4 N5 N6 N7 N8 N9 N0\n"
    "            LSHFT RSHFT\n"
    "        >;\n"
    "        mods = <(MOD_LSFT | MOD_RSFT)>;\n"
    "    };\n"
    "\n"
    "    // Mac-style word navigation with Alt (Option)\n"
    "    alt_left_word: alt_left_word {\n"
    '        compatible = "zmk,behavior-mod-morph";\n'
    "        #binding-cells = <0>;\n"
    "        bindings = <&kp LC(LEFT)>, <&kp LEFT>;\n"
    "        mods = <(MOD_LSFT|MOD_LCTL)>;\n"
    "        keep-mods = <(MOD_LSFT|MOD_LCTL)>;\n"
    "    };\n"
    "\n"
    "    alt_right_word: alt_right_word {\n"
    '        compatible = "zmk,behavior-mod-morph";\n'
    "        #binding-cells = <0>;\n"
    "        bindings = <&kp LC(RIGHT)>, <&kp RIGHT>;\n"
    "        mods = <(MOD_LSFT|MOD_LCTL)>;\n"
    "        keep-mods = <(MOD_LSFT|MOD_LCTL)>;\n"
    "    };\n"
    "\n"
    "    // Mac-style Shift + Backspace for Delete\n"
    "    alt_bspc_del_morph: alt_bspc_del_morph {\n"
    '        compatible = "zmk,behavior-mod-morph";\n'
    "        #binding-cells = <0>;\n"
    "        bindings = <&kp LC(BSPC)>, <&kp LC(DEL)>;\n"
    "        mods = <(MOD_LSFT|MOD_RSFT)>;\n"
    "    };\n"
    "\n"
    "    cmd_bspc_del_morph: cmd_bspc_del_morph {\n"
    '        compatible = "zmk,behavior-mod-morph";\n'
    "        #binding-cells = <0>;\n"
    "        bindings = <&cmd_backspace>, <&cmd_delete>;\n"
    "        mods = <(MOD_LSFT|MOD_RSFT)>;\n"
    "    };\n"
    "\n"
    "};\n"
    "\n"
    "macros {\n"
    "\n"
    "    // Delete line left (Cmd+Backspace)\n"
    "    cmd_backspace: cmd_backspace {\n"
    '        label = "&CMD_BACKSPACE";\n'
    '        compatible = "zmk,behavior-macro";\n'
    "        #binding-cells = <0>;\n"
    "        bindings = <&macro_press &kp LSHFT>, <&macro_tap &kp HOME>, "
    "<&macro_release &kp LSHFT>, <&macro_tap &kp BSPC>;\n"
    "    };\n"
    "\n"
    "    // Delete line right (Cmd+Delete)\n"
    "    cmd_delete: cmd_delete {\n"
    '        label = "&CMD_DELETE";\n'
    '        compatible = "zmk,behavior-macro";\n'
    "        #binding-cells = <0>;\n"
    "        bindings = <&macro_press &kp LSHFT>, <&macro_tap &kp END>, "
    "<&macro_release &kp LSHFT>, <&macro_tap &kp DEL>;\n"
    "    };\n"
    "};",
    "custom_devicetree": '&mt {\n    flavor = "tap-preferred";\n    tapping-term-ms = <220>;\n};',
    "config_parameters": [
        {"paramName": "BLE_BAS", "value": "y"},
        {"paramName": "HID_POINTING", "value": "y"},
        {"paramName": "EXPERIMENTAL_RGB_UNDERGLOW_AUTO_OFF_USB", "value": "y"},
    ],
    "layout_parameters": {},
}

LAYER_NAMES = [
    "Base",
    "HRM",
    "Original",
    "Lower",
    "Mouse",
    "MouseSlow",
    "MouseFast",
    "MouseWarp",
    "Magic",
    "LeftIndex",
    "LeftMiddle",
    "LeftRing",
    "LeftPinky",
    "RightIndex",
    "RightMiddle",
    "RightRing",
    "RightPinky",
]

MACROS = [
    {
        "name": "&BHRM_L_Pinky_Hold",
        "description": "Hold: activate Left Pinky layer",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_press", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="LeftPinky"), "params": []}]},
            {"value": "&macro_pause_for_release", "params": []},
            {"value": "&macro_release", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="LeftPinky"), "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_L_Pinky_Tap",
        "description": "Tap: restore base key",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_release", "params": []},
            {"value": "&kp", "params": [{"value": "LSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "RCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "LGUI", "params": []}]},
            {"value": "&kp", "params": [{"value": "RGUI", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_L_Ring_Hold",
        "description": "Hold: activate Left Ring layer",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_press", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="LeftRing"), "params": []}]},
            {"value": "&macro_pause_for_release", "params": []},
            {"value": "&macro_release", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="LeftRing"), "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_L_Ring_Tap",
        "description": "Tap: restore base key",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_release", "params": []},
            {"value": "&kp", "params": [{"value": "LSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "RCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "LGUI", "params": []}]},
            {"value": "&kp", "params": [{"value": "RGUI", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&kp", "params": [{"value": "S", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_L_Middle_Hold",
        "description": "Hold: activate Left Middle layer",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_press", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="LeftMiddle"), "params": []}]},
            {"value": "&macro_pause_for_release", "params": []},
            {"value": "&macro_release", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="LeftMiddle"), "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_L_Middle_Tap",
        "description": "Tap: restore base key",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_release", "params": []},
            {"value": "&kp", "params": [{"value": "LSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "RCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "LGUI", "params": []}]},
            {"value": "&kp", "params": [{"value": "RGUI", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&kp", "params": [{"value": "D", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_L_Index_Hold",
        "description": "Hold: activate Left Index layer",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_press", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="LeftIndex"), "params": []}]},
            {"value": "&macro_pause_for_release", "params": []},
            {"value": "&macro_release", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="LeftIndex"), "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_L_Index_Tap",
        "description": "Tap: restore base key",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_release", "params": []},
            {"value": "&kp", "params": [{"value": "LSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "RCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "LGUI", "params": []}]},
            {"value": "&kp", "params": [{"value": "RGUI", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&kp", "params": [{"value": "F", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_R_Index_Hold",
        "description": "Hold: activate Right Index layer",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_press", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="RightIndex"), "params": []}]},
            {"value": "&macro_pause_for_release", "params": []},
            {"value": "&macro_release", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="RightIndex"), "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_R_Index_Tap",
        "description": "Tap: restore base key",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_release", "params": []},
            {"value": "&kp", "params": [{"value": "LSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "RCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "LGUI", "params": []}]},
            {"value": "&kp", "params": [{"value": "RGUI", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&kp", "params": [{"value": "J", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_R_Middle_Hold",
        "description": "Hold: activate Right Middle layer",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_press", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="RightMiddle"), "params": []}]},
            {"value": "&macro_pause_for_release", "params": []},
            {"value": "&macro_release", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="RightMiddle"), "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_R_Middle_Tap",
        "description": "Tap: restore base key",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_release", "params": []},
            {"value": "&kp", "params": [{"value": "LSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "RCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "LGUI", "params": []}]},
            {"value": "&kp", "params": [{"value": "RGUI", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&kp", "params": [{"value": "K", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_R_Ring_Hold",
        "description": "Hold: activate Right Ring layer",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_press", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="RightRing"), "params": []}]},
            {"value": "&macro_pause_for_release", "params": []},
            {"value": "&macro_release", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="RightRing"), "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_R_Ring_Tap",
        "description": "Tap: restore base key",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_release", "params": []},
            {"value": "&kp", "params": [{"value": "LSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "RCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "LGUI", "params": []}]},
            {"value": "&kp", "params": [{"value": "RGUI", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&kp", "params": [{"value": "L", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_R_Pinky_Hold",
        "description": "Hold: activate Right Pinky layer",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_press", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="RightPinky"), "params": []}]},
            {"value": "&macro_pause_for_release", "params": []},
            {"value": "&macro_release", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
            {"value": "&mo", "params": [{"value": LayerRef(name="RightPinky"), "params": []}]},
        ],
        "params": ["code"],
    },
    {
        "name": "&BHRM_R_Pinky_Tap",
        "description": "Tap: restore base key",
        "waitMs": 0,
        "tapMs": 0,
        "bindings": [
            {"value": "&macro_release", "params": []},
            {"value": "&kp", "params": [{"value": "LSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RSHFT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "RALT", "params": []}]},
            {"value": "&kp", "params": [{"value": "LCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "RCTRL", "params": []}]},
            {"value": "&kp", "params": [{"value": "LGUI", "params": []}]},
            {"value": "&kp", "params": [{"value": "RGUI", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&kp", "params": [{"value": "SEMI", "params": []}]},
            {"value": "&macro_tap", "params": []},
            {"value": "&macro_param_1to1", "params": []},
            {"value": "&kp", "params": [{"value": "A", "params": []}]},
        ],
        "params": ["code"],
    },
]

HOLD_TAPS = [
    {
        "name": "&BHRM_L_Pinky",
        "description": "HRM: tap→key, hold→layer",
        "bindings": ["&BHRM_L_Pinky_Hold", "&kp"],
        "tappingTermMs": 280,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Pinky_Ring",
        "description": "Combo: Pinky + Ring",
        "bindings": ["&kp", "&BHRM_L_Pinky_Tap"],
        "tappingTermMs": 280,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Pinky_Middle",
        "description": "Combo: Pinky + Middle",
        "bindings": ["&kp", "&BHRM_L_Pinky_Tap"],
        "tappingTermMs": 280,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Pinky_Index",
        "description": "Combo: Pinky + Index",
        "bindings": ["&kp", "&BHRM_L_Pinky_Tap"],
        "tappingTermMs": 280,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Ring",
        "description": "HRM: tap→key, hold→layer",
        "bindings": ["&BHRM_L_Ring_Hold", "&kp"],
        "tappingTermMs": 240,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Ring_Pinky",
        "description": "Combo: Ring + Pinky",
        "bindings": ["&kp", "&BHRM_L_Ring_Tap"],
        "tappingTermMs": 240,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Ring_Middle",
        "description": "Combo: Ring + Middle",
        "bindings": ["&kp", "&BHRM_L_Ring_Tap"],
        "tappingTermMs": 240,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Ring_Index",
        "description": "Combo: Ring + Index",
        "bindings": ["&kp", "&BHRM_L_Ring_Tap"],
        "tappingTermMs": 240,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 100,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Middle",
        "description": "HRM: tap→key, hold→layer",
        "bindings": ["&BHRM_L_Middle_Hold", "&kp"],
        "tappingTermMs": 210,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Middle_Pinky",
        "description": "Combo: Middle + Pinky",
        "bindings": ["&kp", "&BHRM_L_Middle_Tap"],
        "tappingTermMs": 210,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Middle_Ring",
        "description": "Combo: Middle + Ring",
        "bindings": ["&kp", "&BHRM_L_Middle_Tap"],
        "tappingTermMs": 210,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Middle_Index",
        "description": "Combo: Middle + Index",
        "bindings": ["&kp", "&BHRM_L_Middle_Tap"],
        "tappingTermMs": 210,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Index",
        "description": "HRM: tap→key, hold→layer",
        "bindings": ["&BHRM_L_Index_Hold", "&kp"],
        "tappingTermMs": 190,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 100,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Index_Pinky",
        "description": "Combo: Index + Pinky",
        "bindings": ["&kp", "&BHRM_L_Index_Tap"],
        "tappingTermMs": 190,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 100,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Index_Ring",
        "description": "Combo: Index + Ring",
        "bindings": ["&kp", "&BHRM_L_Index_Tap"],
        "tappingTermMs": 190,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 100,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_L_Index_Middle",
        "description": "Combo: Index + Middle",
        "bindings": ["&kp", "&BHRM_L_Index_Tap"],
        "tappingTermMs": 190,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 100,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            57,
            56,
            55,
            72,
            73,
            74,
            5,
            6,
            7,
            8,
            16,
            17,
            18,
            19,
            20,
            28,
            29,
            30,
            31,
            32,
            40,
            41,
            42,
            43,
            44,
            58,
            59,
            60,
            61,
            62,
            75,
            76,
            77,
            78,
            9,
            21,
            33,
            45,
            63,
            79,
            52,
            53,
            54,
            70,
            71,
            69,
        ],
    },
    {
        "name": "&BHRM_R_Index",
        "description": "HRM: tap→key, hold→layer",
        "bindings": ["&BHRM_R_Index_Hold", "&kp"],
        "tappingTermMs": 190,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 100,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Index_Middle",
        "description": "Combo: Index + Middle",
        "bindings": ["&kp", "&BHRM_R_Index_Tap"],
        "tappingTermMs": 190,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 100,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Index_Ring",
        "description": "Combo: Index + Ring",
        "bindings": ["&kp", "&BHRM_R_Index_Tap"],
        "tappingTermMs": 190,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 100,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Index_Pinky",
        "description": "Combo: Index + Pinky",
        "bindings": ["&kp", "&BHRM_R_Index_Tap"],
        "tappingTermMs": 190,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 100,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Middle",
        "description": "HRM: tap→key, hold→layer",
        "bindings": ["&BHRM_R_Middle_Hold", "&kp"],
        "tappingTermMs": 210,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Middle_Index",
        "description": "Combo: Middle + Index",
        "bindings": ["&kp", "&BHRM_R_Middle_Tap"],
        "tappingTermMs": 210,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Middle_Ring",
        "description": "Combo: Middle + Ring",
        "bindings": ["&kp", "&BHRM_R_Middle_Tap"],
        "tappingTermMs": 210,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Middle_Pinky",
        "description": "Combo: Middle + Pinky",
        "bindings": ["&kp", "&BHRM_R_Middle_Tap"],
        "tappingTermMs": 210,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            46,
            64,
            65,
            47,
            52,
            51,
            39,
            27,
            15,
            4,
            3,
            2,
            1,
            11,
            23,
            35,
            34,
            48,
            66,
            69,
            70,
            71,
            54,
            53,
            55,
            56,
            57,
            74,
            73,
            72,
            68,
            67,
            49,
            50,
            38,
            26,
            14,
            13,
            25,
            37,
            24,
            12,
            36,
        ],
    },
    {
        "name": "&BHRM_R_Ring",
        "description": "HRM: tap→key, hold→layer",
        "bindings": ["&BHRM_R_Ring_Hold", "&kp"],
        "tappingTermMs": 240,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Ring_Index",
        "description": "Combo: Ring + Index",
        "bindings": ["&kp", "&BHRM_R_Ring_Tap"],
        "tappingTermMs": 240,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Ring_Middle",
        "description": "Combo: Ring + Middle",
        "bindings": ["&kp", "&BHRM_R_Ring_Tap"],
        "tappingTermMs": 240,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Ring_Pinky",
        "description": "Combo: Ring + Pinky",
        "bindings": ["&kp", "&BHRM_R_Ring_Tap"],
        "tappingTermMs": 240,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Pinky",
        "description": "HRM: tap→key, hold→layer",
        "bindings": ["&BHRM_R_Pinky_Hold", "&kp"],
        "tappingTermMs": 280,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Pinky_Index",
        "description": "Combo: Pinky + Index",
        "bindings": ["&kp", "&BHRM_R_Pinky_Tap"],
        "tappingTermMs": 280,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Pinky_Middle",
        "description": "Combo: Pinky + Middle",
        "bindings": ["&kp", "&BHRM_R_Pinky_Tap"],
        "tappingTermMs": 280,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
    {
        "name": "&BHRM_R_Pinky_Ring",
        "description": "Combo: Pinky + Ring",
        "bindings": ["&kp", "&BHRM_R_Pinky_Tap"],
        "tappingTermMs": 280,
        "flavor": "tap-preferred",
        "quickTapMs": 300,
        "requirePriorIdleMs": 150,
        "holdTriggerOnRelease": True,
        "holdTriggerKeyPositions": [
            0,
            10,
            22,
            34,
            46,
            64,
            65,
            47,
            35,
            23,
            1,
            2,
            12,
            11,
            24,
            36,
            48,
            66,
            67,
            49,
            37,
            25,
            13,
            3,
            4,
            14,
            15,
            27,
            26,
            38,
            39,
            51,
            50,
            68,
            52,
            53,
            54,
            71,
            70,
            69,
            55,
            56,
            57,
            74,
            73,
            72,
        ],
    },
]

COMBOS = [
    {
        "name": "combo_enter",
        "description": "E + D for Enter",
        "binding": {"value": "&kp", "params": [{"value": "RET", "params": []}]},
        "keyPositions": [25, 37],
        "timeoutMs": 50,
        "layers": [-1],
    },
    {
        "name": "combo_space",
        "description": "R + F for Enter",
        "binding": {"value": "&kp", "params": [{"value": "SPACE", "params": []}]},
        "keyPositions": [26, 38],
        "timeoutMs": 50,
        "layers": [-1],
    },
    {
        "name": "Hyper",
        "description": "",
        "binding": {"value": "&kp", "params": [{"value": "RGUI", "params": []}]},
        "keyPositions": [69, 70],
        "layers": [-1],
    },
]

INPUT_LISTENERS = [
    {
        "code": "&mmv_input_listener",
        "inputProcessors": [],
        "nodes": [
            {
                "code": "LAYER_MouseSlow",
                "description": "LAYER_MouseSlow",
                "layers": [LayerRef(name="MouseSlow")],
                "inputProcessors": [{"code": "&zip_xy_scaler", "params": [1, 9]}],
            },
            {
                "code": "LAYER_MouseFast",
                "description": "LAYER_MouseFast",
                "layers": [LayerRef(name="MouseFast")],
                "inputProcessors": [{"code": "&zip_xy_scaler", "params": [3, 1]}],
            },
            {
                "code": "LAYER_MouseWarp",
                "description": "LAYER_MouseWarp",
                "layers": [LayerRef(name="MouseWarp")],
                "inputProcessors": [{"code": "&zip_xy_scaler", "params": [12, 1]}],
            },
        ],
    },
    {
        "code": "&msc_input_listener",
        "inputProcessors": [],
        "nodes": [
            {
                "code": "LAYER_MouseSlow",
                "description": "LAYER_MouseSlow",
                "layers": [LayerRef(name="MouseSlow")],
                "inputProcessors": [{"code": "&zip_scroll_scaler", "params": [1, 9]}],
            },
            {
                "code": "LAYER_MouseFast",
                "description": "LAYER_MouseFast",
                "layers": [LayerRef(name="MouseFast")],
                "inputProcessors": [{"code": "&zip_scroll_scaler", "params": [3, 1]}],
            },
            {
                "code": "LAYER_MouseWarp",
                "description": "LAYER_MouseWarp",
                "layers": [LayerRef(name="MouseWarp")],
                "inputProcessors": [{"code": "&zip_scroll_scaler", "params": [12, 1]}],
            },
        ],
    },
]
